server:
  port: 8084

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /admin/swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/admin_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    listener:
      simple:
        missing-queues-fatal: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
